# /.github/workflows/deploy.yml
name: Deploy to GHCR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Generate unique tag
      id: tag
      run: echo "tag=$(date +%Y%m%d-%H%M%S)-${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./aigoya
        push: true
        no-cache: true
        build-args: |
          BUILD_DATE=${{ github.run_number }}-${{ github.sha }}
        tags: |
          ghcr.io/likelion-13th-aigoya/frontend:latest
          ghcr.io/likelion-13th-aigoya/frontend:${{ steps.tag.outputs.tag }}
    
    - name: Image digest
      run: echo "Image pushed with digest ${{ steps.build.outputs.digest }}"
